import { readFileSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { products } from '../src/utils/products'

const __dirname = dirname(fileURLToPath(import.meta.url))

const readmeFilePath = join(__dirname, '..', 'README.md')

const productCount = products.length
const productListMarkdown = products
	.map(product => `- [${product.name}](${product.website})`)
	.join('\n')

let readmeContent = readFileSync(readmeFilePath, 'utf-8')

const header = '## Autogenerated Product List'
const headerIndex = readmeContent.indexOf(header)

if (headerIndex !== -1) {
	readmeContent = readmeContent.substring(0, headerIndex + header.length)
} else {
	readmeContent += `\n${header}`
}

readmeContent += `\n\nTotal Products: ${productCount}\n\n${productListMarkdown}\n`

writeFileSync(readmeFilePath, readmeContent, 'utf-8')

console.log('README.MD updated successfully!') 