import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const productsFilePath = path.join(__dirname, '..', 'data', 'products.json');
const readmeFilePath = path.join(__dirname, '..', 'README.MD');

const products = JSON.parse(fs.readFileSync(productsFilePath, 'utf-8'));

const productCount = products.length;
const productListMarkdown = products
    .map(product => `- [${product.name}](${product.website})`)
    .join('\n');

// Read README.MD
let readmeContent = fs.readFileSync(readmeFilePath, 'utf-8');

const header = '## Autogenerated Product List';
const headerIndex = readmeContent.indexOf(header);

if (headerIndex !== -1) {
    readmeContent = readmeContent.substring(0, headerIndex + header.length);
} else {
    readmeContent += `\n${header}`;
}

readmeContent += `\n\nTotal Products: ${productCount}\n\n${productListMarkdown}\n`;

fs.writeFileSync(readmeFilePath, readmeContent, 'utf-8');

console.log('README.MD updated successfully!');